---
title: "regressed-integration"
author: "Taran"
date: "2026-08-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(harmony)
library(Seurat)
library(dplyr)
library(cowplot)
library(Matrix)
library(ggplot2)
options(bitmapType = "cairo")

```


read full reg obj data
```{r}


HH28A <- readRDS("/nobackup/proj/comet_icnlmdhuc/Taran/chicken_RNA_seq/HH28/sample_1/sObj/sObj_6_full_regression.RDS")
HH28B <- readRDS("/nobackup/proj/comet_icnlmdhuc/Taran/chicken_RNA_seq/HH28/sample_2/sObj/sObj_6_full_reg.RDS")
HH28C <- readRDS("/nobackup/proj/comet_icnlmdhuc/Taran/chicken_RNA_seq/HH28/sample_3/sObj/sObj_6_full_reg.RDS")
HH28D <- readRDS("/nobackup/proj/comet_icnlmdhuc/Taran/chicken_RNA_seq/HH28/sample_4/sObj/sObj_6_full_reg.RDS")

```

#set orig.ident so Harmony has something to integrate over
```{r}

HH28A$orig.ident <- "HH28A"
HH28B$orig.ident <- "HH28B"
HH28C$orig.ident <- "HH28C"
HH28D$orig.ident <- "HH28D"
```


########### add individual cell type annotations to each seurat object

## HH28A
```{r}
anno_A <- read.csv(
  "/nobackup/proj/comet_icnlmdhuc/Taran/chicken_RNA_seq/HH28/annotations/HH28A/HH28A-full.txt"
)

anno_A$cell_type <- gsub("\\s+", "", anno_A$cell_type)

HH28A$original_annotation <- anno_A$cell_type[
  match(HH28A$RNA_snn_res.0.6, anno_A$cluster)
]
```

## HH28B
```{r}
anno_B <- read.csv(
  "/nobackup/proj/comet_icnlmdhuc/Taran/chicken_RNA_seq/HH28/annotations/HH28B/HH28B-full.txt"
)

anno_B$cell_type <- gsub("\\s+", "", anno_B$cell_type)

HH28B$original_annotation <- anno_B$cell_type[
  match(HH28B$RNA_snn_res.0.5, anno_B$cluster)
]
```


## HH28C
```{r}
anno_C <- read.csv(
  "/nobackup/proj/comet_icnlmdhuc/Taran/chicken_RNA_seq/HH28/annotations/HH28C/HH28C-full.txt"
)

anno_C$cell_type <- gsub("\\s+", "", anno_C$cell_type)

HH28C$original_annotation <- anno_C$cell_type[
  match(HH28C$RNA_snn_res.0.6, anno_C$cluster)
]
```


## HH28D
```{r}
anno_D <- read.csv(
  "/nobackup/proj/comet_icnlmdhuc/Taran/chicken_RNA_seq/HH28/annotations/HH28D/HH28D-full.txt"
)

anno_D$cell_type <- gsub("\\s+", "", anno_D$cell_type)

HH28D$original_annotation <- anno_D$cell_type[
  match(HH28D$RNA_snn_res.0.5, anno_D$cluster)
]
```


#merge into one object
```{r}

HH28 <- merge(HH28A, y = list (HH28B, HH28C, HH28D))

```


#pre-processing
```{r}
HH28 <- NormalizeData(HH28)
HH28 <- FindVariableFeatures(HH28, selection.method = "vst", nfeatures = 2000)
HH28 <- ScaleData(HH28, vars.to.regress = c("S.Score", "G2M.Score"), features = VariableFeatures(HH28))
HH28 <- RunPCA(HH28, features = VariableFeatures(HH28), npcs = 50)

```


# Integrate over a single batch variable
```{r}
HH28 <- RunHarmony(
  object         = HH28,
  group.by.vars  = "orig.ident",        # or e.g. "batch", "donor"
  reduction.use  = "pca",
  dims.use       = 1:30,                # choose PCs to harmonize
  reduction.save = "harmony",
  project.dim    = TRUE
)

```


# UMAP
```{r}
HH28 <- RunUMAP(HH28, reduction = "harmony", dims = 1:30)

# Nearest neighbours and clustering
HH28 <- FindNeighbors(HH28, reduction = "harmony", dims = 1:30)
HH28 <- FindClusters(HH28, resolution = c(0.4, 0.5, 0.6, 0.7))

```

#UMAP trial
```{r}h

res <- "RNA_snn_res."
nums = c(0.4, 0.5, 0.6, 0.7)
paste0(res, nums)

DimPlot(HH28, reduction = "umap", label = TRUE, repel = TRUE, group.by = paste0(res, nums), pt.size = 0.5)
ggsave("/nobackup/proj/comet_icnlmdhuc/Taran/chicken_RNA_seq/HH28/integration/full-reg/plots/full-int-30-umap-trial-.png", dpi = 400, width =60, height = 35, units = "cm")

```

##reorder to alphanumeric
```{r}
HH28$original_annotation <- factor(HH28$original_annotation,levels = stringr::str_sort(unique(HH28$original_annotation), numeric=TRUE))
```

#plot UMAP
```{r}

DimPlot(HH28, reduction = "umap", label = TRUE, repel = TRUE, group.by = "original_annotation", pt.size = 0.5)
ggsave("/nobackup/proj/comet_icnlmdhuc/Taran/chicken_RNA_seq/HH28/integration/full-reg/plots/full-int-cell-ant.png", dpi = 400, width =60, height = 35, units = "cm")

```


```{r}h

saveRDS(HH28, file = "/nobackup/proj/comet_icnlmdhuc/Taran/chicken_RNA_seq/HH28/integration/full-reg/sObj/sObj_HH28-full-int.RDS")

```

```{r}

saveRDS(HH28, file = "/nobackup/proj/comet_icnlmdhuc/Taran/chicken_RNA_seq/HH28/integration/full-reg/sObj/sObj_HH28-cell-ant-full-int.RDS")

```
